version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>.0
          install-yarn: true
          install-npm: false
      - run: yarn test.prod

  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          matrix:
            parameters:
              os:
                - linux
              node-version:
                - "12.9"
                - "14.9"
      - release:
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - test
