on:
  push:
    branches:
      - master
      - beta
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '10.18'
          - '12.x'
          - '14.x'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn lint
      - run: yarn test
